# Generated by Django 3.0.8 on 2020-07-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200717_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='accounts', verbose_name='Avatar'),
        ),
    ]
